trailingComma: 'all'
tabWidth: 4
printWidth: 100
semi: false
singleQuote: true
overrides:
  - files: '*.php'
    options:
      phpVersion: '8.1'
      trailingCommaPHP: true
      braceStyle: '1tbs'
      tabWidth: 4
